language: node_js
node_js:
  - '8'
  - '10'
  - '12'



addons:
  postgresql: '9.6'

services:
  - postgresql

before_install:
  - npm install npm --global

env:
  - PGVERSION=9.6 PGUSER=postgres PGDATABASE=postgres

before_script:
  - sudo bash -c "echo 'host replication all    127.0.0.1/32  trust' >> /etc/postgresql/$PGVERSION/main/pg_hba.conf"
  - sudo bash -c "echo >> /etc/postgresql/$PGVERSION/main/postgresql.conf"
  - sudo bash -c "echo 'max_wal_senders = 1' >> /etc/postgresql/$PGVERSION/main/postgresql.conf"
  - sudo systemctl postgresql restart
